info:
  name: ${spring.application.name}
  description: Configuration Server registered in Eureka that retrieves config files from a git repo
  version: 1.0
  language: Kotlin
  project:
    description: Spring Boot, Spring Cloud & Netflix OSS Microservice Architecture POC
    git: https://github.com/xcapdevila/msarchitecture-poc-kotlin
  author:
    name: Xavier Capdevila Estevez
    git: https://github.com/xcapdevila
    linkedin: https://www.linkedin.com/in/xcapdevila/
  license: CC BY-NC-SA

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: 'DEBUG'
    io.capdevila: 'TRACE'

server:
  port: ${PORT:8888}

management:
  security:
    enabled: ${SECURE:false}

spring:
  application:
    name: ${APPLICATION_NAME:configserver}
  boot:
    admin:
      username: 'admin'
      password: 'admin1234'
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_FILES:file://${user.home}/mspoc-config}
          #ADD GIT HUB URI uri: ${CONFIG_FILES:file://${user.home}/mspoc-config}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest